csatar-plugins/forms/assets/css/storm.css
csatar-plugins/forms/components/BasicForm.php
csatar-plugins/forms/lang/en/lang.php
csatar-plugins/forms/models/Form.php
csatar-plugins/forms/models/form/columns.yaml
csatar-plugins/forms/models/form/fields.yaml
csatar-plugins/forms/plugin.yaml
csatar-plugins/forms/updates/builder_table_update_csatar_forms_forms.php
csatar-plugins/forms/updates/seeder_109.php
csatar-plugins/forms/updates/version.yaml
csatar-theme/pages/csapat.htm
csatar-theme/pages/korzet.htm
csatar-theme/pages/ors.htm
csatar-theme/pages/raj.htm
csatar-theme/pages/szovetseg.htm
csatar-theme/pages/tag.htm

CS-131 Changed form builder plugin to use slugs instead of form id and added seeder to update existing forms
+ Updated existing pages where form builder is used
+ Removed unused code
+ Prepared css file for CS-146 task
+ Added icon for plugin

CS-131 change form builder component to use slug

---

csatar-theme/assets/css/csatar-custom-styles.css

Anna-Mari észrevételei alapján:
- a keresőben - más input és form mezőkben illetve gombok körül a kék keret/shadow eltűntetve
- a jelszó mezőben megoldva, hogy ne jelenjen meg 2 szem

CS-110_Apply_design_system_for_login_page

---

csatar-theme/assets/css/csatar-custom-styles.css

Anna-Maria üzenete alapján annyit módosítottam, hogy mobil nézetben most a fiúcska és a kislány illusztrációk középezve vannak.

CS-137_404_500_pages_design

---

csatar-theme/partials/site/meta.htm

- added solution for CSS caching problem

CS-159 added solution for CSS chacing problem

---

csatar-theme/partials/site/header.htm

- Changed the order of the logo and the menu on mobile view.

CS-90 apply the design system for home page merge conf fix

---

csatar-plugins/forms/components/BasicForm.php
csatar-plugins/forms/traits/AjaxControllerSimple.php
csatar-plugins/forms/traits/ManagesUploads.php

Cs 196 fix the form errors

---

csatar-plugins/csatar/components/resetpassword/complete.htm
csatar-plugins/csatar/components/resetpassword/reset.htm
csatar-plugins/csatar/components/resetpassword/set.htm

Applied design for:
- reset
- set
- complete

CS-200 Applied design for forgotten password pages

---

csatar-plugins/csatar/components/resetpassword/reset.htm
csatar-plugins/csatar/components/resetpassword/restore.htm
csatar-plugins/csatar/components/resetpassword/set.htm
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/partials/account/signin.htm

- updated design system
- updated login and reset password pages

CS-200 Fixed text sizes

---

csatar-plugins/forms/components/BasicForm.php
csatar-plugins/forms/components/basicform/partials/form.htm
csatar-plugins/forms/components/basicform/partials/relationOptions.htm
csatar-plugins/forms/lang/en/lang.php
csatar-plugins/forms/lang/hu/lang.php
csatar-plugins/forms/traits/AjaxControllerSimple.php
csatar-plugins/forms/traits/ManagesUploads.php

Fixed deferred binding in forms opened on multiple tabs.

Cs-124 Belongs to many relations with deffered binding

---

csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/partials/DesignSystem/flash-messages.htm
csatar-theme/partials/DesignSystem/table.htm

CS-180 font correction and added flash messages to design system

Cs 180 flash messages font correction

---

csatar-theme/assets/css/csatar-custom-styles.css

CS-239 Visual search button hidden

CS-239 Hid hover button in MS Edge

---

Changelog.md
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/association/columns.yaml
csatar-plugins/csatar/models/association/fields.yaml
csatar-plugins/csatar/updates/SeederData.php
csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_associations_2.php
csatar-plugins/csatar/updates/version.yaml

Added name abbreviation to association model and updated seeder

CS-189 Added name abbreviation to association model and updated seeder

---

Changelog.md
csatar-plugins/csatar/components/organizationunitfrontend/associationForm.htm
csatar-plugins/csatar/components/organizationunitfrontend/districtForm.htm
csatar-plugins/csatar/components/organizationunitfrontend/teamForm.htm
csatar-plugins/csatar/components/organizationunitfrontend/troopForm.htm
csatar-plugins/forms/components/BasicForm.php
csatar-theme/pages/csapatjelentes.htm
csatar-theme/pages/csapatjelentesek.htm

Applied basic permissions:
- only logged in user can create/update/delete records
- only logged in user are able to see team reports

CS-193 Applied basic permissions:

---

Changelog.md
csatar-plugins/csatar/controllers/Trainings.php
csatar-plugins/csatar/controllers/trainings/_list_toolbar.htm
csatar-plugins/csatar/controllers/trainings/config_form.yaml
csatar-plugins/csatar/controllers/trainings/config_list.yaml
csatar-plugins/csatar/controllers/trainings/create.htm
csatar-plugins/csatar/controllers/trainings/index.htm
csatar-plugins/csatar/controllers/trainings/preview.htm
csatar-plugins/csatar/controllers/trainings/update.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/LeadershipQualification.php
csatar-plugins/csatar/models/Scout.php
csatar-plugins/csatar/models/ScoutLeadershipQualificationPivot.php
csatar-plugins/csatar/models/ScoutTrainingQualificationPivot.php
csatar-plugins/csatar/models/Training.php
csatar-plugins/csatar/models/TrainingQualification.php
csatar-plugins/csatar/models/leadershipqualification/columnsPivot.yaml
csatar-plugins/csatar/models/leadershipqualification/fieldsPivot.yaml
csatar-plugins/csatar/models/training/columns.yaml
csatar-plugins/csatar/models/training/fields.yaml
csatar-plugins/csatar/models/trainingqualification/columnsPivot.yaml
csatar-plugins/csatar/models/trainingqualification/fieldsPivot.yaml
csatar-plugins/csatar/plugin.yaml
csatar-plugins/csatar/updates/SeederData.php
csatar-plugins/csatar/updates/builder_table_create_csatar_csatar_trainings.php
csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_scouts_leadership_qualifications.php
csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_scouts_training_qualifications.php
csatar-plugins/csatar/updates/version.yaml

- Added training list Model, backend CRUD
- Added  dropdown for LearderShipQualification and TrainingQualification and updated pivot tables

CS-178 create leadership trainig list

---

csatar-plugins/csatar/models/Association.php
csatar-plugins/csatar/models/District.php
csatar-plugins/csatar/models/Patrol.php
csatar-plugins/csatar/models/Scout.php
csatar-plugins/csatar/models/Team.php
csatar-plugins/csatar/models/TeamReport.php
csatar-plugins/csatar/models/TeamReportScoutPivot.php
csatar-plugins/csatar/models/Troop.php
csatar-plugins/forms/assets/js/positionValidationTags.js
csatar-plugins/forms/components/BasicForm.php
csatar-plugins/forms/components/basicform/partials/form.htm
csatar-plugins/forms/traits/AjaxControllerSimple.php

CS-228 Fixed auto update for related dropdowns
+ made legal_relationship required for Scout model because the above change makes it possible

CS-228 fix related dropdown updates

---

Changelog.md
csatar-plugins/forms/components/BasicForm.php
csatar-plugins/forms/components/basicform/partials/form.htm
csatar-plugins/forms/lang/en/lang.php
csatar-plugins/forms/lang/hu/lang.php
csatar-plugins/forms/traits/AjaxControllerSimple.php

CS-150 Added redirect to previous page after form "save and close" and "close" and flash message on "save"

CS-150 redirect after form save close

---

Changelog.md
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/partials/DesignSystem/cards.htm
csatar-theme/partials/DesignSystem/grid.htm

- Changed grid solution using cards
- Deleted earlier grid solution from design system
- Fixed cards bottom rounded corner
- Fixed Form field height (added min-height)

CS-229 design manyToMany

---

Changelog.md

- Added OauthException class to handle exceptions
- oAuth exceptions are thrown and cached in Plugin.php

CS-199 Extended social login plugin to handle Scount and User model connections

---

Changelog.md
csatar-theme/assets/css/csatar-custom-styles.css

- Modified the position of the flash messages, depending on the screen size

CS-277 - Modified the position of flash messages

---

Changelog.md
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/partials/DesignSystem/typography.htm

- styled the explanatory text (help-block class)

CS-278 styling of the "help-block" class

---

csatar-theme/assets/css/csatar-custom-styles.css

- removed line from css which prevented the link to appear on images.

CS-294 Corrected link on img error

---

Changelog.md
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/partials/DesignSystem/grid.htm

- Changed color of Grid based table heading

- CS-279 - Changed color of Grid heading

---

csatar-theme/assets/css/csatar-custom-styles.css

- Fixed an error where in case of multiple lines, the cells of the grid weren't the same height.
- Increased padding of content in cell

CS-229 Fixed grid cell height

---

csatar-plugins/csatar/classes/ContentPageSearchProvider.php
csatar-plugins/csatar/controllers/seederdata/seeder.htm
csatar-plugins/csatar/controllers/seederdata/test.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/permissionsmatrix/_3option_select.htm
csatar-plugins/csatar/updates/SeederData.php
csatar-plugins/csatar/updates/TestData.php

Added plugin settings to seeder.

CS-68 missing seeder search plugin settings

---

Changelog.md
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/pages/design-system.htm
csatar-theme/partials/DesignSystem/breadcrumb.htm

CS-247 added breadcrumb design

---

Changelog.md
csatar-plugins/csatar/components/csatargallery/galleryImages.htm
csatar-plugins/csatar/components/logos/default.htm
csatar-plugins/csatar/components/organizationunitfrontend/default.htm
csatar-plugins/csatar/components/structure/accordionItems.htm
csatar-plugins/forms/assets/js/addCheckboxClass.js
csatar-plugins/forms/components/BasicForm.php
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/pages/kapcsolat.htm
csatar-theme/partials/site/header.htm

- Changed user symbol on site header
- Changed text size for sponsors on main page
- Changed thickness of accordion bar on main page
- Changed header color for grid table
- Redesigned the contact page
- Corrected text appearance in calendar box
- Corrected checkbox design

CS-299 - Design changes and corrections part1

---

Changelog.md
csatar-plugins/csatar/Plugin.php
csatar-plugins/csatar/classes/validators/CnpValidator.php
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/Association.php
csatar-plugins/csatar/models/Scout.php
csatar-plugins/csatar/models/association/fields.yaml
csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_associations_3.php
csatar-plugins/csatar/updates/version.yaml

- Created Personal Identification Number Validator class
- Created option on Associations form to select validator
- Scout's Personal Identification Number Validator gets validation if validator is set for Association
Note: added blank line in changelog.md because other items in Unreleased section are released.

CS-244 Created Personal Identification Number Validator

---

Changelog.md
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/partials/DesignSystem/breadcrumb.htm

- modified breadcrumb design in the design system

CS-247 modified breadcrumb design

---

csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/partials/DesignSystem/breadcrumb.htm
csatar-theme/partials/site/breadcrumb.htm
csatar-theme/partials/site/layout.htm

- modified breadcrumb design and position
- made breadcrumb scrollable

CS-247 Modified breadcrumb design and position

---

csatar-plugins/forms/components/basicform/partials/mainCard.htm
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/partials/DesignSystem/cards.htm

- Corrected profile image ellipse display error

CS-299 Corrected profile img ellipse display error

---

Changelog.md
csatar-theme/assets/csat-jquery/csat-menu.js
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/pages/design-system.htm
csatar-theme/partials/DesignSystem/menu.htm
csatar-theme/partials/site/meta.htm

- modified navigation bar to support multi-level
- added navigation bar to design system

CS-302 Multi-level navigation

---

csatar-plugins/csatar/models/MandateType.php
csatar-plugins/csatar/models/Scout.php
csatar-plugins/csatar/models/association/fields.yaml
csatar-plugins/csatar/models/district/fields.yaml
csatar-plugins/csatar/models/scout/fields.yaml
csatar-plugins/csatar/updates/SeederData.php
csatar-plugins/forms/components/basicform/partials/mainCard.htm
csatar-plugins/forms/traits/AjaxControllerSimple.php

CS-186, CS-329, CS-334, a szövegváltoztatás CS-310-ből

Cs 186 redesign the form builder view mode

---

csatar-plugins/csatar/controllers/PermissionsMatrix.php
csatar-plugins/csatar/controllers/permissionsmatrix/config_filter.yaml
csatar-plugins/csatar/controllers/permissionsmatrix/config_form.yaml
csatar-plugins/csatar/controllers/permissionsmatrix/config_list.yaml
csatar-plugins/csatar/models/MandatePermission.php
csatar-plugins/csatar/models/MandateType.php
csatar-plugins/csatar/models/Scout.php
csatar-plugins/csatar/updates/SeederData.php
csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_mandates_permissions_2.php
csatar-plugins/csatar/updates/version.yaml

- Added soft delete to MandatePermission
- When MandateType is soft deleted all it's MandatePermission are soft deleted as well
- When MandateType is hard deleted all it's MandatePermission are hard deleted as well

CS-310 - Refactored PermissionsMatrix to MandatePermission

---

Changelog.md
csatar-plugins/csatar/models/Scout.php
csatar-plugins/forms/traits/AjaxControllerSimple.php

CS-338 - Reduced EcsetCode length to 6 characters + separator + suffix.
- Fixed bug on form builder

CS-338 - Reduced EcsetCode length to 6 characters + separator + suffix.

---

csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/scout/fields.yaml

- Removed required status for tshirt size on scout form
- Added comment to profile image on scout form

CS-328 - Removed required status for tshirt size on scout form

---

csatar-plugins/csatar/components/Structure.php
csatar-plugins/csatar/components/structure/default.htm
csatar-plugins/csatar/components/structure/menuItems.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-theme/pages/index.htm
csatar-theme/partials/site/header.htm

Created menu for organization structure

CS-169 - Created menu for organization structure

---

csatar-plugins/csatar/Plugin.php
csatar-plugins/csatar/components/TwoFactorAuthentication.php
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/Scout.php

- Implemented 2FA in getRightsForModel function
- Modified redirect after 2FA authentication to the page before 403 error

CS-287 Implemented 2fa in getRightsForModel function

---

Changelog.md
csatar-plugins/csatar/Plugin.php
csatar-plugins/csatar/classes/GoogleTwoFactorAuthentication.php
csatar-plugins/csatar/components/TwoFactorAuthentication.php
csatar-plugins/csatar/components/twofactorauthentication/default.htm
csatar-plugins/csatar/components/twofactorauthentication/success.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/Scout.php
csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_scouts_2.php
csatar-plugins/csatar/updates/version.yaml
csatar-theme/layouts/basicAuth.htm
csatar-theme/layouts/default.htm
csatar-theme/layouts/twoFactorAuth.htm
csatar-theme/partials/site/header.htm

- Implemented two-factor authentication
- Added Plugin dependencies

CS-36 implement 2FA

---

Changelog.md
csatar-plugins/csatar/components/structure/menuItems.htm
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/partials/DesignSystem/menu.htm
csatar-theme/partials/site/header.htm

- added navigation overlay for submenus on desktop view
- reorganized navigation on tablet view
- added off-canvas sidebar on mobile view
- visual updates

CS-302 Updated and optimized navbar display

---

Changelog.md
csatar-plugins/csatar/classes/AccidentLogRigthsProvider.php
csatar-plugins/csatar/classes/UserRigthsProvider.php
csatar-plugins/csatar/controllers/seederdata/seeder.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/AccidentLogRecord.php
csatar-plugins/csatar/models/PermissionBasedAccess.php
csatar-plugins/csatar/updates/SeederData.php
csatar-plugins/forms/components/BasicForm.php
csatar-theme/partials/site/header.htm

- Created menu items for accident log
- Created seeder for accident log user groups
- Implemented rights for accident log user groups

CS-297 - Implemented UserRigthsProvider class

---

csatar-plugins/csatar/controllers/Mandates.php
csatar-plugins/csatar/controllers/mandates/_list_toolbar.htm
csatar-plugins/csatar/controllers/mandates/config_filter.yaml
csatar-plugins/csatar/controllers/mandates/config_form.yaml
csatar-plugins/csatar/controllers/mandates/config_list.yaml
csatar-plugins/csatar/controllers/mandates/create.htm
csatar-plugins/csatar/controllers/mandates/index.htm
csatar-plugins/csatar/controllers/mandates/preview.htm
csatar-plugins/csatar/controllers/mandates/update.htm
csatar-plugins/csatar/models/MandateType.php
csatar-plugins/csatar/models/Scout.php
csatar-plugins/csatar/plugin.yaml

C-S-360 limit manadetes to organization structure

---

csatar-plugins/csatar/components/CheckScoutStatus.php
csatar-plugins/csatar/components/checkscoutstatus/default.htm

- Changed scout status check to display name for logged in user
- Added district link

CS-330 - Changed scout status check to display name for logged in user

---

csatar-plugins/csatar/components/structure/menuItems.htm
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/partials/site/header.htm

- reduced the width to 90%
- added transition effect
- added word wrap possibility for long names on small screens
- added search bar to the navigation on small screens
- linked the logo in the navigation to the front page

CS-302 Tweaking of the nav design on small screens

---

Changelog.md
csatar-plugins/csatar/controllers/PermissionsMatrix.php
csatar-plugins/csatar/controllers/permissionsmatrix/_list_toolbar.htm
csatar-plugins/csatar/controllers/permissionsmatrix/config_import_export.yaml
csatar-plugins/csatar/controllers/permissionsmatrix/export.htm
csatar-plugins/csatar/controllers/permissionsmatrix/import.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/PermissionExport.php
csatar-plugins/csatar/models/PermissionImport.php
csatar-plugins/csatar/models/permissionexport/columns.yaml
csatar-plugins/csatar/models/permissionexport/fields.yaml
csatar-plugins/csatar/models/permissionimport/columns.yaml
csatar-plugins/csatar/models/permissionsmatrix/columns2.yaml
csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_mandates_permissions_3.php
csatar-plugins/csatar/updates/version.yaml

Created csv import-export for permissions matrix.

CS-378 Created csv import-export for permissions matrix.

---

csatar-plugins/csatar/components/Breadcrumb.php
csatar-plugins/csatar/components/CreateFrontendAccounts.php
csatar-plugins/csatar/components/CsatarGallery.php

CS-325 - Made breadcrumb shorter

---

Changelog.md
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/partials/site/header.htm
csatar-theme/partials/site/layout.htm
csatar-theme/partials/site/navigation.htm

- moved navigation below main logo, search bar and controls row
- modified hamburger menu so it is activated on tablet view

CS-302 Reorganized navigation to fit more items

---

csatar-plugins/csatar/components/CreateFrontendAccounts.php
csatar-plugins/csatar/components/checkscoutstatus/default.htm
csatar-plugins/csatar/components/teamreport/additionalData.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/scout/fields.yaml
csatar-plugins/forms/components/BasicForm.php
csatar-plugins/forms/traits/AjaxControllerSimple.php
csatar-theme/partials/account/register.htm
csatar-theme/partials/account/signin.htm
setup/dev/Dockerfile

- Displayed ID number on scout's view page
- Fixed form builder permissions handling bug for fields that have no permission information
- Added option to ignore user rights settings if set so in model's fields yaml file

CS-392 - Renamed ECSET code to ID number

---

Changelog.md
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/Team.php
csatar-plugins/csatar/models/team/fields.yaml
csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_teams.php
csatar-plugins/csatar/updates/version.yaml
csatar-plugins/forms/components/BasicForm.php
csatar-plugins/forms/traits/AjaxControllerSimple.php

Added and implemented status field to team

CS-399 - Added and implemented status field to team

---

Changelog.md
csatar-plugins/csatar/controllers/mandates/config_filter.yaml
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/Mandate.php
csatar-plugins/csatar/models/Scout.php
csatar-plugins/csatar/models/mandate/columns.yaml
csatar-plugins/csatar/models/scout/fields.yaml
csatar-plugins/csatar/views/pdf/layouts/teamreportlayout.htm
csatar-plugins/forms/traits/AjaxControllerSimple.php

Extended backend mandates list with "mandate_model_name", "mandate_team", "scout_team" columns and added filters for every column

CS-351 Extended backend mandates list

---

Changelog.md
Readme.md
csatar-plugins/csatar/components/CreateFrontendAccounts.php
csatar-plugins/csatar/controllers/JsonImport.php
csatar-plugins/csatar/controllers/SeederData.php
csatar-plugins/csatar/controllers/seederdata/synchronizepermissionsmatrix.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/District.php
csatar-plugins/csatar/models/Patrol.php
csatar-plugins/csatar/models/Troop.php
csatar-plugins/csatar/models/team/fields.yaml
csatar-plugins/csatar/plugin.yaml

- Created method to automatically add newly added field s to permission matrix
- CS-414 - Fixed "felhasznaloi-fiok-letrehozasa" page permissions bug
- CS-400 - File attachment errors on json import
- CS-400 - Fixed team import error for team existing in different district

CS-416 add newly created fields to permissions matrix

---

csatar-plugins/csatar/controllers/JsonImport.php
csatar-plugins/csatar/controllers/jsonimport/mandates.htm
csatar-plugins/csatar/models/Scout.php
csatar-plugins/csatar/plugin.yaml
csatar-plugins/csatar/updates/update_mandate_types_add_is_vk_column.php
csatar-plugins/csatar/updates/version.yaml

Import mandate types and mandates from json

CS-419 import mandate types and mandates

---

csatar-plugins/csatar/controllers/JsonImport.php
csatar-plugins/csatar/controllers/jsonimport/promises.htm
csatar-plugins/csatar/plugin.yaml

Promises, qualifications, etc. json import

CS-420 - Promises, qualifications, etc. json import

---

Changelog.md
csatar-plugins/csatar/components/structure/menuItems.htm
csatar-theme/assets/css/csatar-custom-styles.css

- changed navbar position
- added scrollbar to 3 level submenu
- changed scrollbar design

CS-423 Fixed navigation, changed scrollbar design

---

Changelog.md
csatar-plugins/csatar/Plugin.php
csatar-plugins/csatar/controllers/seederdata/test.htm
csatar-plugins/csatar/updates/SeederData.php
csatar-plugins/csatar/updates/TestData.php

- fixed SeederData, removed permissions seeding from main seeder, removed association data overwrite
- fixed Plugin.php to run boot method only after specific plugin version

CS-434 - Fixed SeederData

---

csatar-plugins/csatar/controllers/JsonImport.php
csatar-plugins/csatar/controllers/jsonimport/registrationforms.htm
csatar-plugins/csatar/plugin.yaml

Created page to import registration files for scouts

CS-433 - Created page to import registration files for scouts

---

Changelog.md
csatar-plugins/csatar/controllers/MembershipCards.php
csatar-plugins/csatar/controllers/membershipcards/_list_toolbar.htm
csatar-plugins/csatar/controllers/membershipcards/config_form.yaml
csatar-plugins/csatar/controllers/membershipcards/config_list.yaml
csatar-plugins/csatar/controllers/membershipcards/create.htm
csatar-plugins/csatar/controllers/membershipcards/index.htm
csatar-plugins/csatar/controllers/membershipcards/preview.htm
csatar-plugins/csatar/controllers/membershipcards/update.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/MembershipCard.php
csatar-plugins/csatar/models/Scout.php
csatar-plugins/csatar/models/membershipcard/columns.yaml
csatar-plugins/csatar/models/membershipcard/fields.yaml
csatar-plugins/csatar/plugin.yaml
csatar-plugins/csatar/updates/builder_table_create_csatar_csatar_membership_cards.php
csatar-plugins/csatar/updates/version.yaml

Created and implemented Membership Card model

CS-418 - Created and implemented Membership Card model

---

Changelog.md
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/Scout.php
csatar-plugins/csatar/models/scout/columns.yaml
csatar-plugins/csatar/models/scout/fields.yaml
csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_scouts_3.php
csatar-plugins/csatar/updates/version.yaml

Added "is_approved" field for Scout

CS-432 Added "is_approved" field for Scout

---

Changelog.md
csatar-plugins/csatar/components/structure/menuItems.htm
csatar-plugins/csatar/models/Association.php

Hide associations without teams from menu

CS-429 hide associations without teams from menu

---

Changelog.md
csatar-plugins/csatar/components/structure/accordionItems.htm
csatar-plugins/csatar/models/Team.php

Order teams on district page by team number

CS-417 - Order teams on district page by team number

---

Changelog.md
csatar-plugins/csatar/components/TwoFactorAuthentication.php
csatar-plugins/csatar/controllers/Scouts.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_scouts_3.php
csatar-plugins/csatar/updates/version.yaml
csatar-theme/assets/css/csatar-custom-styles.css

CS-440 - Fixed missing QR code for 2FA

---

Changelog.md
csatar-plugins/csatar/models/Mandate.php
csatar-plugins/csatar/models/Scout.php
csatar-plugins/csatar/models/mandate/columns.yaml
csatar-plugins/forms/traits/AjaxControllerSimple.php

Hide inactive and expired mandates on Association, District, Team, Troop, Patrol pages

CS-424 Hide inactive and expired mandates

---

Changelog.md
csatar-plugins/csatar/components/organizationunitfrontend/default.htm
csatar-plugins/csatar/models/association/fields.yaml
csatar-theme/assets/css/csatar-custom-styles.css

- Changed accordion to tabs on organizations page
- Added missing 'formBuilder_card_design: true' setting to association fields config

CS-443 - Changed accordion to tabs on organizations page

---

Changelog.md
csatar-plugins/csatar/components/OrganizationUnitFrontend.php
csatar-plugins/csatar/components/organizationunitfrontend/associationForm.htm
csatar-plugins/csatar/components/organizationunitfrontend/default.htm
csatar-plugins/csatar/components/organizationunitfrontend/districtForm.htm
csatar-plugins/csatar/components/organizationunitfrontend/inactiveMandates.htm
csatar-plugins/csatar/components/organizationunitfrontend/patrolForm.htm
csatar-plugins/csatar/components/organizationunitfrontend/teamForm.htm
csatar-plugins/csatar/components/organizationunitfrontend/troopForm.htm
csatar-plugins/csatar/models/Mandate.php
csatar-plugins/csatar/models/OrganizationBase.php

Added "Inactive mandates" accordion to Association, District, Team, Troop, Patrol pages

CS-441 - Added "Inactive mandates" accordion to organizations

---

Changelog.md
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/pages/design-system.htm
csatar-theme/partials/DesignSystem/two-factor-auth.htm

- added design to 2FA information
- added key icon to 2FA form control

CS-358 - Added 2FA design elements

---

Changelog.md
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/pages/adatvedelmi-iranyelvek.htm

Updated Terms and conditions page

CS-148 modify term and conditions page

---

Changelog.md
csatar-plugins/csatar/components/TeamReport.php
csatar-plugins/csatar/components/teamreport/default.htm
csatar-plugins/csatar/components/teamreports/default.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/TeamReport.php
csatar-plugins/forms/components/basicform/partials/form.htm

Added "Refresh" and "Delete" buttons to team reports, to allow refresh/delete when team report is not submitted

CS-456 hotfix teamreports add refresh delete

---

csatar-theme/assets/css/csatar-custom-styles.css

- Changed the overlap amount of the submenu
- The overlap is now at 40% of the parent menu list

CS-423 Changed the overlap amount of the submenu

---

Changelog.md
csatar-theme/assets/css/csatar-custom-styles.css

- The form on mobile view is now displayed on a single column, instead of two
- Fixed overflow problem for dropdown boxes on mobile view

CS-412 - Fixed dropdown boxes on mobile view

---

Changelog.md
csatar-plugins/csatar/components/TeamReports.php
csatar-plugins/csatar/components/accidentlogrecordlist/default.htm
csatar-plugins/csatar/components/accidentlogrecordlist/listItem.htm
csatar-plugins/csatar/components/checkscoutstatus/default.htm
csatar-plugins/csatar/components/createfrontendaccounts/default.htm
csatar-plugins/csatar/components/csatargallery/create.htm
csatar-plugins/csatar/components/csatargallery/default.htm
csatar-plugins/csatar/components/organizationunitfrontend/activeTagsList.htm
csatar-plugins/csatar/components/organizationunitfrontend/associationForm.htm
csatar-plugins/csatar/components/organizationunitfrontend/districtForm.htm
csatar-plugins/csatar/components/organizationunitfrontend/inactiveTagsList.htm
csatar-plugins/csatar/components/organizationunitfrontend/patrolForm.htm
csatar-plugins/csatar/components/organizationunitfrontend/teamForm.htm
csatar-plugins/csatar/components/organizationunitfrontend/troopForm.htm
csatar-plugins/csatar/components/partials/dataRequestButton.htm
csatar-plugins/csatar/components/partials/formButton.htm
csatar-plugins/csatar/components/partials/formWithButton.htm
csatar-plugins/csatar/components/partials/simpleATagButton.htm
csatar-plugins/csatar/components/teamreport/default.htm
csatar-plugins/csatar/components/teamreports/reportsOfATeam.htm
csatar-plugins/csatar/components/teamreports/waitingForApproval.htm
csatar-plugins/forms/components/basicform/partials/relationOptions.htm
csatar-plugins/forms/lang/en/lang.php
csatar-plugins/forms/lang/hu/lang.php
csatar-plugins/forms/traits/AjaxControllerSimple.php

- Added buttons partial
- Buttons partial can handle passed permission value
- Changed buttons on every component to one of the buttons partial, expect gallery

Cs-458 make all buttons uniform

---

Changelog.md
csatar-plugins/csatar/classes/CsvCreator.php
csatar-plugins/csatar/components/AccidentLogRecordList.php
csatar-plugins/csatar/components/TeamReports.php
csatar-plugins/csatar/controllers/MembershipCardRequests.php
csatar-plugins/csatar/controllers/membershipcardrequests/_list_toolbar.htm
csatar-plugins/csatar/controllers/membershipcardrequests/config_list.yaml
csatar-plugins/csatar/controllers/membershipcardrequests/index.htm
csatar-plugins/csatar/controllers/membershipcards/_list_toolbar.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/MembershipCardRequest.php
csatar-plugins/csatar/models/membershipcardrequest/columns.yaml
csatar-theme/pages/balesetek-csv-letoltes.htm

CS-461 - Created backend list with scouts, who are have "Tag" legal relationship and belong are present in a submitted team report, but doesn't have membership card
- Minor fixes

CS-461 - Created membership card requests backend list

---

Changelog.md
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/Mandate.php
csatar-plugins/csatar/models/mandatetype/fields.yaml
csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_mandate_types.php
csatar-plugins/csatar/updates/version.yaml
csatar-plugins/forms/traits/AjaxControllerSimple.php
setup/dev/init.sh

Added option to hide mandate types on frontend

CS-436 Added option to hide mandate types on frontend

---

Changelog.md
csatar-plugins/csatar/components/TeamReport.php
csatar-plugins/csatar/components/TeamReports.php
csatar-plugins/csatar/components/teamreport/additionalData.htm
csatar-plugins/csatar/components/teamreport/default.htm
csatar-plugins/csatar/models/TeamReport.php

Added warning to team report if any scout doesn't have registration form uploaded

CS-462 - Added warning to team report

---

Changelog.md
csatar-plugins/csatar/classes/BackendExtensions.php
csatar-plugins/csatar/controllers/MandateTypes.php
csatar-plugins/csatar/controllers/Scouts.php
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/MandateType.php
csatar-plugins/csatar/models/Scout.php

Fixed success/error message issue on back list bulk delete

CS-363 - Fixed success/error message issue on back list bulk delete

---

csatar-plugins/csatar/Plugin.php
csatar-plugins/csatar/assets/touch-dnd.js
csatar-plugins/csatar/components/CsatarGallery.php
csatar-plugins/csatar/components/csatargallery/default.htm
csatar-plugins/csatar/components/csatargallery/galleryImages.htm
csatar-plugins/csatar/components/csatargallery/sortOrder.htm
csatar-plugins/csatar/components/partials/formButton.htm
csatar-plugins/csatar/updates/migration_1077.php
csatar-plugins/csatar/updates/version.yaml
csatar-theme/assets/vendor/bootstrap-5.1.3/css/bootstrap.css

CS-311 - Created sort order method for the galleries
- Created new form where can change the order between the galleries or images from a galery

CS-311 - Created sort order method for the galleries

---

Changelog.md
csatar-plugins/csatar/components/Structure.php
csatar-plugins/csatar/components/organizationunitfrontend/patrolForm.htm
csatar-plugins/csatar/components/organizationunitfrontend/teamForm.htm
csatar-plugins/csatar/components/organizationunitfrontend/troopForm.htm
csatar-plugins/csatar/components/structure/accordionbody.htm
csatar-plugins/csatar/components/structure/buttonList.htm
csatar-plugins/csatar/components/structure/default.htm
csatar-plugins/csatar/models/Patrol.php
csatar-plugins/csatar/models/Team.php
csatar-plugins/csatar/models/Troop.php

- Removed functionality buttons from the 'reszletek' section on the team/troop/patrol pages
- Added these buttons to the 'kapcsolati szintek section' 
- Added active tag lists to the 'kapcsolati szintek' and removed from the 'reszletek'
- Removed duplicated patrols on the team page 'kapcsolati szintek' section
- Taglists was added only on the model pages (example: on the homepage the structure has displayed without the tag lists)

CS-397 - Changed accordion on the team,patrol and troop pages

---

Changelog.md
csatar-plugins/csatar/classes/CsvCreator.php
csatar-plugins/csatar/classes/enums/Gender.php
csatar-plugins/csatar/classes/enums/InjurySeverity.php
csatar-plugins/csatar/classes/enums/Status.php
csatar-plugins/csatar/classes/mappers/LegalRelationshipMapper.php
csatar-plugins/csatar/classes/mappers/ReligionMapper.php
csatar-plugins/csatar/components/AccidentLogRecordList.php
csatar-plugins/csatar/components/OrganizationUnitFrontend.php
csatar-plugins/csatar/components/organizationunitfrontend/csvImportLog.htm
csatar-plugins/csatar/components/organizationunitfrontend/csvUploadForm.htm
csatar-plugins/csatar/components/organizationunitfrontend/teamForm.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/AccidentLogRecord.php
csatar-plugins/csatar/models/Mandate.php
csatar-plugins/csatar/models/Scout.php
csatar-theme/assets/css/csatar-custom-styles.css
csatar-theme/pages/csv-letoltes.htm

Cherry pick csv import-export from develop

CS-460 - Cherry pick csv import-export from develop

---

Changelog.md
csatar-plugins/csatar/components/OrganizationUnitFrontend.php
csatar-plugins/csatar/components/organizationunitfrontend/inactiveMandates.htm
csatar-plugins/csatar/models/Association.php
csatar-plugins/csatar/models/District.php
csatar-plugins/csatar/models/Mandate.php
csatar-plugins/csatar/models/OrganizationBase.php
csatar-plugins/csatar/models/Patrol.php
csatar-plugins/csatar/models/Team.php
csatar-plugins/csatar/models/Troop.php

- Optimized query for inactive mandates
- Modified inactive mandates accordion according to the changes

CS-498 optimized inactive mandates accordion

---

csatar-plugins/csatar/models/Association.php
csatar-plugins/csatar/models/District.php
csatar-plugins/csatar/models/OrganizationBase.php
csatar-plugins/csatar/models/Patrol.php
csatar-plugins/csatar/models/Scout.php
csatar-plugins/csatar/models/Team.php
csatar-plugins/csatar/models/Troop.php

- Fixed incorrect cache update process
- Created updateCache() method to OrganizationBase models to separate cache update process from other after save actions

CS-502 - Fixed incorrect cache update process

---

Changelog.md
csatar-plugins/csatar/models/TeamReport.php
csatar-plugins/csatar/models/TeamReportAgeGroupPivot.php
csatar-plugins/csatar/models/agegroup/fieldsPivot.yaml

- On team report Age Group editing, made Number of Patrols in Age Group field required, for this I created a TeamReportAgeGroupPivot model

CS-497 - Number of Patrols in Age Group field required

---

csatar-plugins/forms/components/BasicForm.php
csatar-plugins/knowledgerepository/models/Methodology.php
csatar-plugins/knowledgerepository/models/methodology/approverscout.htm
csatar-plugins/knowledgerepository/models/methodology/fields.yaml
csatar-plugins/knowledgerepository/models/methodology/uploaderscout.htm
csatar-theme/pages/tudastar/modszertan.htm

- Fixed date fields to can save as null.
- Fixed age group - association relation
- Fixed uploader/approver scout displaying

CS-377 - Fixed methodology create/edit form

---

Changelog.md
Readme.md
csatar-theme/manifest.json
csatar-theme/partials/site/meta.htm

- Added `manifest.json` file and updated readme with instructions on how to add PWA support

CS-331 Added PWA support - 1*

---

Changelog.md
csatar-plugins/csatar/classes/BackendExtensions.php
csatar-plugins/csatar/controllers/Scouts.php
csatar-plugins/csatar/controllers/scouts/_list_toolbar.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/Scout.php

Added option to backend scout list to (soft)delete scout with personal data

CS-475 - Added option to delete scout with personal data - 1*

---

csatar-plugins/forms/components/basicform/partials/pivotSection.htm
csatar-plugins/forms/components/basicform/partials/pivotTableHeader.htm
csatar-plugins/forms/components/basicform/partials/pivotTableRow.htm
csatar-plugins/forms/components/basicform/partials/pivotTableRowCol.htm
csatar-plugins/forms/components/basicform/partials/pivotTableRowColButtons.htm
csatar-plugins/forms/components/basicform/partials/relationOptions.htm
csatar-plugins/forms/components/basicform/partials/validationTags.htm
csatar-plugins/forms/traits/AjaxControllerSimple.php

- Moved validation tags from AjaxControllerSimple.php to validationTags.htm partial
- Fixed validation when adding new belongsToMany relations
- Added pivotSection.htm partial and moved pivot section html from AjaxControllerSimple.php to partial
- Added pivotTableHeader.htm, pivotTableRow.htm, pivotTableRowCol.htm, pivotTableRowColButtons.htm partials and moved their html from AjaxControllerSimple.php to partial

CS-553 Move html to partial from formbuilder trait

---

csatar-plugins/csatar/Plugin.php
csatar-plugins/csatar/classes/OrganizationSearchProvider.php

- Modified search results to display results starting with Scouts to Association and last results from Content page

CS-533 - Modified search results to display order

---

csatar-plugins/csatar/models/Mandate.php
csatar-plugins/csatar/models/Scout.php
csatar-theme/pages/tag.htm

- Added inactive mandates to scout's page

CS-394 - Added inactive mandates to scout's page

---

Changelog.md
csatar-plugins/csatar/Plugin.php
csatar-plugins/csatar/controllers/Scouts.php
csatar-plugins/csatar/controllers/scouts/_list_toolbar.htm
csatar-plugins/csatar/controllers/scouts/_list_toolbar_trashed.htm
csatar-plugins/csatar/controllers/scouts/config_list_trashed.yaml
csatar-plugins/csatar/controllers/scouts/deleted.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/Scout.php

- Added restore deleted scouts option on backend
- Added inactivation on scout soft deleted

CS-500 - Restore deleted scouts on backend

---

Changelog.md
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/Patrol.php
csatar-plugins/csatar/models/patrol/fields.yaml
csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_patrols_3.php
csatar-plugins/csatar/updates/version.yaml
csatar-plugins/knowledgerepository/models/WorkPlan.php

- Added Trial System Trial Type to patrol
- Extended team Work Plan patrols field to include information about patrol's Trial System Trial Type

CS-563 - Added Trial System Trial Type to patrol

---

Changelog.md
csatar-plugins/knowledgerepository/classes/xlsx/GamesXlsxImport.php
csatar-plugins/knowledgerepository/classes/xlsx/SongsXlsxImport.php
csatar-plugins/knowledgerepository/classes/xlsx/TrialSystemsXlsxImport.php
csatar-plugins/knowledgerepository/controllers/Games.php
csatar-plugins/knowledgerepository/controllers/Songs.php
csatar-plugins/knowledgerepository/controllers/TrialSystems.php
csatar-plugins/knowledgerepository/controllers/songs/_import_errors.htm
csatar-plugins/knowledgerepository/controllers/songs/_list_toolbar.htm
csatar-plugins/knowledgerepository/controllers/songs/create.htm
csatar-plugins/knowledgerepository/controllers/songs/import.htm
csatar-plugins/knowledgerepository/lang/en/lang.php
csatar-plugins/knowledgerepository/lang/hu/lang.php

- Added xlsx import for Songs.
- Fixed error handling on TrialSystems xlsx import
- Fixed missing approved_at date on Games xlsx import.

CS-530 - Added xlsx import for Songs.

---

csatar-plugins/csatar/components/organizationunitfrontend/default.htm
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php
csatar-plugins/csatar/models/Troop.php
csatar-plugins/csatar/models/troop/fields.yaml
csatar-plugins/knowledgerepository/components/WorkPlansList.php
csatar-plugins/knowledgerepository/models/OvamtvWorkPlan.php
csatar-theme/pages/raj.htm

- Added Workplans tab to Troops page
- Updated WorkPlansList to display worksplans tab on Troops page
- Added sorting WorkPlansList by start_date
- Removed comma after last item in patrol members default value

CS-562 - Added Workplans tab to Troops page

---

Changelog.md
csatar-plugins/csatar/models/AgeGroup.php
csatar-plugins/csatar/models/Allergy.php
csatar-plugins/csatar/models/ChronicIllness.php
csatar-plugins/csatar/models/FoodSensitivity.php
csatar-plugins/csatar/models/LeadershipQualification.php
csatar-plugins/csatar/models/LegalRelationship.php
csatar-plugins/csatar/models/Locations.php
csatar-plugins/csatar/models/ModelExtended.php
csatar-plugins/csatar/models/Promise.php
csatar-plugins/csatar/models/Religion.php
csatar-plugins/csatar/models/SpecialDiet.php
csatar-plugins/csatar/models/SpecialQualification.php
csatar-plugins/csatar/models/SpecialTest.php
csatar-plugins/csatar/models/Test.php
csatar-plugins/csatar/models/Training.php
csatar-plugins/csatar/models/TrainingQualification.php
csatar-plugins/knowledgerepository/models/AccidentRiskLevel.php
csatar-plugins/knowledgerepository/models/FolkSongRhythm.php
csatar-plugins/knowledgerepository/models/FolkSongType.php
csatar-plugins/knowledgerepository/models/GameDevelopmentGoal.php
csatar-plugins/knowledgerepository/models/GameType.php
csatar-plugins/knowledgerepository/models/MethodologyType.php
csatar-plugins/knowledgerepository/models/SongType.php
csatar-plugins/knowledgerepository/models/Tool.php
csatar-plugins/knowledgerepository/models/TrialSystemCategory.php
csatar-plugins/knowledgerepository/models/TrialSystemSubTopic.php
csatar-plugins/knowledgerepository/models/TrialSystemTopic.php
csatar-plugins/knowledgerepository/models/TrialSystemTrialType.php
csatar-plugins/knowledgerepository/models/TrialSystemType.php

- Created ModelExtended base model with getNameAttribute method, that returns name attribute with ucfirst
- Changed every "Scout systemdata" and "Knowledge repository parameter" model's base model to ModelExtended

- CS-413 - Created ModelExtended base model with getNameAttribute method

---

csatar-plugins/forms/traits/AjaxControllerSimple.php
csatar-plugins/knowledgerepository/models/Methodology.php
csatar-plugins/knowledgerepository/models/game/columns.yaml
csatar-plugins/knowledgerepository/models/methodology/columnsRecordList.yaml
csatar-theme/pages/tudastar/jatekok.htm
csatar-theme/pages/tudastar/modszertanok.htm

- Added recordList component to frontend Games and Methodologies page
- Removed unnecessary Pivot model settings from Methodologies relations
- Fixed from builder bug: on empty taglist submit, relation was not removed from model

CS-545 - Added recordList component to frontend Games and Methodologies

---

Changelog.md
csatar-plugins/csatar/components/recordlist/tableRow.htm
csatar-plugins/csatar/components/recordlist/tableRows.htm

- Improved pagination in record list component
- Fixed row height in record list component

CS-570 - Improved pagination in record list component

---

csatar-plugins/csatar/Plugin.php
csatar-plugins/csatar/lang/en/lang.php
csatar-plugins/csatar/lang/hu/lang.php

Fixed frontend user delete error, when user has scout or history entries, added appropriate error message.

CS-581 - Fixed frontend user delete error

---

csatar-plugins/forms/components/BasicForm.php
csatar-plugins/knowledgerepository/views/pdf/layouts/weeklyworkplanlayout.htm

- removed hr from the end of weekly workplan pdf template

CS-564 - Fixed css injection for taglist in readonly mode

---

csatar-plugins/csatar/classes/StructureTree.php
csatar-plugins/csatar/classes/UserRigthsProvider.php
csatar-plugins/csatar/components/Structure.php
csatar-plugins/csatar/components/structure/accordionItems.htm
csatar-plugins/csatar/components/structure/menuItems.htm
csatar-plugins/csatar/controllers/PermissionsMatrix.php
csatar-plugins/csatar/models/PermissionBasedAccess.php

Showing structure item in accordion and menu for guest user based on permissions

CS-602 - Showing structure items based on permissions

---

csatar-plugins/csatar/models/Scout.php

Added method to update User's email address if Scout's email address changed

CS-621 Added method to update User's email address if Scout's email address changed
